---
title: "Homework 6"
output: github_document
---

```{r library import, echo = FALSE, message = FALSE}
library(tidyverse)
set.seed(1)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
## Problem 1
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
set.seed(1)

bootstrap_weather = 
  weather_df %>%   
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin, data = df)),
    results = map(models, broom::tidy),
    fit = map(models, broom::glance))
```

```{r}
bootstrap_results = 
  bootstrap_weather%>%
  unnest(results) %>% 
  select(term, estimate, fit) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  mutate(
    log_betas = log(`(Intercept)`* tmin)
  ) %>% 
  unnest(fit) %>% 
  select(log_betas, adj.r.squared)
```
## Plotting distribution of the estimate
```{r}
bootstrap_results %>% 
  ggplot(aes(x = adj.r.squared)) + 
  geom_histogram() + 
  labs(
    title = "Distribution of adjusted R-squared",
    x = "Adjusted R Squared",
    y = "Frequency"
  )

bootstrap_results %>% 
  ggplot(aes(x = log_betas)) +
  geom_histogram()+
  labs(
    title = "Distribution of log (B0 * B1)",
    x = "log (B0 * B1)",
    y = "Frequency"
  )
```
We can observe that both of the plots, the adjusted R-squared and the log (B0 * B1) demonstrate normal distributions. 

```{r}
bootstrap_results %>%
  summarize(
    ci_lower_r2 = quantile(adj.r.squared, 0.025), 
    ci_upper_r2 = quantile(adj.r.squared, 0.975),
    ci_lower_betas = quantile(log_betas, 0.025), 
    ci_upper_betas = quantile(log_betas, 0.975)
  ) %>% 
  unite("adjusted R_squared confidence interval", ci_lower_r2:ci_upper_r2, sep = ", ") %>% 
  unite("log product of betas confidence interval", ci_lower_betas:ci_upper_betas, sep = ", ") %>% 
  knitr::kable()
```
## Problem 2

```{r}
homicide = read.csv("data/homicide-data.csv") %>% 
  unite("city_state", city:state, sep = ', ', na.rm = TRUE)%>% 
  mutate(
    city_state = str_replace(city_state, "Milwaukee, wI", "Milwaukee, WI"),
    victim_age = as.numeric(victim_age),
    unsolved = ifelse(disposition %in% c("Closed without arrest", "Open/No arrest"), 0, 1)
  ) %>% 
  filter(
    !(city_state %in% c("Dallas, TX", "Phoenix, AZ", "Kansas City, MO", "Tulsa, AL")),
    victim_race %in% c("White", "Black")
  )
```

## glm
```{r}
baltimore =
  homicide %>% 
  filter(city_state == "Baltimore, MD") 

baltimore_glm = 
  baltimore%>% 
  glm(unsolved ~ victim_age + victim_race + victim_sex, data =., family = binomial()) %>% 
  broom::tidy(conf.int = TRUE) %>% 
  mutate(
    OR = exp(estimate)) %>% 
  select(term, log_OR = estimate, OR, conf.low, conf.high) %>% 
  knitr::kable(digits = 4)

```
## each cities
```{r}
glm_city = function(df) {
    glm(unsolved ~ victim_age + victim_race + victim_sex, data =df, family = binomial()) %>%
    broom::tidy() %>%
    mutate(
    OR = exp(estimate),
    CI_low = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
    )
}

city_state_glm = 
  homicide %>% 
  select(city_state, unsolved, victim_race, victim_age, victim_sex) %>% 
  nest(data = unsolved:victim_sex) %>% 
  mutate(
    glm_result = map(data,glm_city)
    ) %>%
  filter(term == "victim_sexMale") %>% 
  unnest(glm_result) %>% 
  select(term, log_OR = estimate, OR, conf.low, conf.high)



```

# Problem 3
```{r}
birthweight = read_csv("data/birthweight.csv") %>% 
  mutate(
    babysex = as.factor(babysex),
    babysex = case_match(babysex,
      1 ~ "male",
      2 ~ "female"
    ),
    frace = case_match(
      frace,
      1 ~ "White",
      2~ "Black",
      3 ~ "Asian", 
      4 ~ "Puerto Rican",
      8 ~ "Other",
      9 ~ "Unknown"
    ),
    malform = case_match(
      malform,
      0 ~ "absent",
      1 ~ "present"
    ),
    mrace = case_match(
      mrace,
      1 ~ "White",
      2 ~ "Black",
      3 ~ "Asian",
      4 ~ "Puerto Rican",
      8 ~ "Other"
    )) %>% 
  drop_na()
```

